{% set name = "secml" %}
{% set version = "0.15.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/secml-{{ version }}.tar.gz
  sha256: 25ab54358e3780e8c17fb4c49c51c4ded0723400fd1c2417835311a3ea3282cf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5,<3.9
  run:
    - joblib >=0.14
    - matplotlib-base >=3
    - numpy >=1.17
    - pillow >=6.2.1
    - python >=3.5,<3.9
    - python-dateutil
    - requests
    - scikit-learn >=0.22
    - scipy >=1.3.2

test:
  imports:
    - secml
    - secml.adv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://secml.gitlab.io
  summary: A library for Secure and Explainable Machine Learning
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Walter-0
    - mxr-conda
